### ISSUE TITLE
igraph output

### ISSUE THREAD

**Issue by noamross** [r-lib/pkgdepends#106]
For visualization and analysis, it would be helpful to have the dependency structure of a package as an igraph object.  Would it be possible to create the method for this?  Or, if you wish to avoid the dependency, perhaps an output suitable for processing by one for the `*_from_data_frame()` functions.

**Comment by gaborcsardi** [comment]
We can think about this, but in general I don't the usual graph layouts are useful for this. It is also a big dependency. Since the (hard) dependency tree must be a DAG, maybe some Sankey diagram is better.

**Comment by gaborcsardi** [comment]
pkgdepends can now draw dependency trees, so I am going to close this, if you don't mind.

<img width="525" alt="Screen Shot 2019-12-10 at 11 52 41 AM" src="https://user-images.githubusercontent.com/660288/70529365-4526fe00-1b48-11ea-9a83-b38b4f9c41dd.png">
