### ISSUE TITLE
Possible to install to a new directory?

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#162]
Hi Gabor,

I'm hoping to use this package as the backend for [checkpoint](https://github.com/RevolutionAnalytics/checkpoint). Basically, checkpoint scans your project and then installs any required packages from a specified MRAN snapshot into a custom directory.

I was looking through the docs for `pkg_installation_proposal` and didn't see any way to specify a location for installing the packages -- it just defaults to the 1st entry in `.libPaths()`. Is there a way to tell pkgdepends where to install?

Hope the virus thing isn't affecting you too badly....

**Comment by gaborcsardi** [comment]
Hi, yeah, it is a bit hidden in the config, see `?pkg_config`:

```r
new_pkg_installation_proposal(..., config = list(library = "new-library"))
...
```

**Comment by Hong-Revo** [comment]
Oh, thanks. I thought that was for scanning for existing packages though?

**Comment by gaborcsardi** [comment]
Both.
