### ISSUE TITLE
Suggestion: allow manually setting no. of install workers

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#166]
Currently, `ps::ps_cpu_count()` [returns NA on Win 10](https://github.com/r-lib/ps/issues/77), as does `getOption("Ncpus")`. This means that `new_pkg_installation_proposal$install()` will default to using only one worker. Until the core detection is working, consider allowing the no. of workers to be set in the `install` call, so that parallel installs can be carried out on Windows.

It goes the other way too: if you're installing packages that require compiling C++ code, you may not want to have lots of them running in parallel. In this situation, reducing the no. of workers would be a way to reduce the chances of running out of memory.

**Comment by Hong-Revo** [comment]
I see that `install_package_plan` allows setting the number of workers, but is there any reason why the R6 method isn't the same? It's a bit odd that there are regular functions and also methods to do the same thing.

**Comment by gaborcsardi** [comment]
You can set the `Ncpus` option to the desired number.
