### ISSUE TITLE
Caching confusion with multiple package versions

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#168]
Related to https://github.com/r-lib/pkgcache/issues/39. I thought at first that pkgcache can't handle multiple package versions, but it appears that it does. However, I'm finding that downloading and/or installing multiple versions can screw up.

Here, I attempt to install tibble first from the MRAN snapshot for 2020-03-01, and then from 2019-03-01. I deleted the R-pkg dir first to ensure that the cache was clean.

```r
inst <- new_pkg_installation_proposal(
    "tibble",
    config=list(`cran-mirror`="https://mran.microsoft.com/snapshot/2020-03-01",
                library="~/tibble2020")
)
inst$resolve()
inst$solve()
inst$download()
inst$install()
```
```r
inst2 <- new_pkg_installation_proposal(
    "tibble",
    config=list(`cran-mirror`="https://mran.microsoft.com/snapshot/2019-03-01",
                library="~/tibble2019")
)
inst2$resolve()
inst2$solve()
inst2$download()
inst2$install()
```

Afterwards, the installed version of tibble is the same in both directories:

```
r$> grep("^Version",
         readLines(system.file("DESCRIPTION", package="tibble", lib.loc="~/tibble2020")), value=TRUE)
[1] "Version: 2.1.3"

r$> grep("^Version",
         readLines(system.file("DESCRIPTION", package="tibble", lib.loc="~/tibble2019")), value=TRUE)
[1] "Version: 2.1.3"
r$>
```

If you go to the MRAN snapshot sites, you'll see that the correct tibble version at [2019-03-01](https://cran.microsoft.com/snapshot/2019-03-01/web/packages/tibble/) was 2.0.1.

**Comment by Hong-Revo** [comment]
This behaviour isn't consistent for all the packages involved, some of them (pillar and cli) have been downloaded from the older snapshot.

**Comment by Hong-Revo** [comment]
It looks like this is because of the .Rprofile file. On my machine, ~/.Rprofile contains the line

```
options(repos="https://cloud.r-project.org")
```

and this is causing pkgdepends to download from that location. Removing the file results in the correct (older) tibble version being installed.

**Comment by gaborcsardi** [comment]
Well, that's expected then, I guess.

**Comment by Hong-Revo** [comment]
Well, no; I specify `cran-mirror` in the config, so I would expect packages to be downloaded from there.

**Comment by gaborcsardi** [comment]
R does not know that `options(repos="https://cloud.r-project.org")` is a CRAN repo, so `cran-mirror` will not override that (apparently). Try writing 

```
options(repos = c(CRAN = "https://cloud.r-project.org"))
```

in your profile, `cran-mirror` should override that.

**Comment by Hong-Revo** [comment]
What do you mean by R doesn't know that is a CRAN repo? It knows enough to download from there when I run `install.packages`.

In any case, this seems like a really fragile fix. I'm surely not the only one who's been leaving names out of my repo setting all this time. Can pkgdepends be made robust against this problem?

**Comment by gaborcsardi** [comment]
pkgdepends has no way to know that a repo in your `repos` option is for CRAN, unless you name it CRAN in that vector.

> Can pkgdepends be made robust against this problem?

So should pkgdepends just ignore your extra repos in `repos`? I am not sure if that's a good solution.

**Comment by Hong-Revo** [comment]
One solution might be to treat any unnamed repo as a CRAN repo. That should handle the vast majority of such cases.

Also, in the reprex, pkgdepends ignores the unnamed repo for cli and pillar, so it does get it right some of the time.

**Comment by gaborcsardi** [comment]
The convention is to name the CRAN repo CRAN, see in 'Writing R Extensions' and also in `?options`. 

I don't think pkgdepends ignores the unnamed repo, but the solver might end up using a package from another repo, because it is already in the cache, or just by  chance. pkgdepends certainly does not use a different set of repos for different packages.

**Comment by Hong-Revo** [comment]
The _convention_ may be to name it "CRAN" (and says who?), but that's certainly not a _requirement_. And `?options` doesn't say you should do it that way either, it simply gives an example where it's named.

**Comment by Hong-Revo** [comment]
Also: if you run the code above (with `options(repos=*)` in .Rprofile), you should find that cli and pillar are indeed installed from the MRAN 2019-03-01 snapshot. So it's doing the right thing and using the specified cran-mirror for these packages. The question is why it isn't doing it for all the other packages.

**Comment by Hong-Revo** [comment]
The best solution might simply be, if the same package is found on a cran-mirror config and on a regular repo, then use the one from the cran-mirror. I don't know how pkgdepends handles dupes in general though.

**Comment by Hong-Revo** [comment]
Per email, wrapping the installation in `withr::with_options(list(repos=NULL), ...)` solved this problem.
