### ISSUE TITLE
Resolving an installed:: ref fails if the library of the ref is not the target library

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#169]
Trying out something other than regular CRAN references. This causes an error on my Win 10 machine. R6 itself has no dependencies, so I'd have thought it would be a fairly easy task.

```r
inst <- new_pkg_installation_proposal("installed::/Rlib/R6",
    config=list(library=c("~/newlib")))
inst$resolve()
inst$solve()
inst$get_solution()
```
```
<pkg_solution>
+ result: FAILED
+ refs:
  - installed::/Rlib/R6
+ constraints (2):
  - select R6 exactly once
  - `installed::/Rlib/R6` resolution failed
x failures:
  x Cannot install `installed::/Rlib/R6`.
    - replacement has 1 row, data has 0
```

Running `inst$get_resolution()` and digging around ultimately produces

```
r$> inst$get_resolution()$error[[1]]
<async_rejected in `$<-.data.frame`(`*tmp*`, "direct", value = TRUE): replacement has 
1 row, data has 0>
```

**Comment by gaborcsardi** [comment]
(Closed by accident)

For an `installed::` package, the installed location must be the same as the library you are installing to. pkgdepends does not copy installed packages to another library. (Although that's an interesting idea now that packages are supposed to be relocatable.) E.g.

```r
inst <- new_pkg_installation_proposal(
  "installed::/Users/Gabor/Documents/R/win-library/3.6/ps"
)
inst$resolve()
inst$get_resolution()

#> # A tibble: 1 x 27
#>   ref   type  direct directpkg status package version license needscompilation
#>   <chr> <chr> <lgl>  <lgl>     <chr>  <chr>   <chr>   <chr>   <lgl>
#> 1 "ins~ inst~ TRUE   TRUE      OK     ps      1.3.2   BSD_3_~ TRUE
#> # ... with 18 more variables: priority <chr>, md5sum <chr>, sha256 <chr>,
#> #   filesize <int>, built <chr>, platform <chr>, rversion <chr>, repodir <chr>,
#> #   target <chr>, deps <list>, mirror <chr>, sources <list>, remote <list>,
#> #   error <list>, metadata <list>, extra <list>, dep_types <list>,
#> #   cache_status <chr>

.libPaths()
#> [1] "C:/Users/Gabor/Documents/R/win-library/3.6"
#> [2] "c:/Program Files/R/R-3.6.3/library"
```

**Comment by Hong-Revo** [comment]
Yeah, it would be very useful to have a way to relax that condition. I'm guessing it's there as a constraint for the solver?

My checkpoint use case is if the user has a package that isn't on CRAN or any other repo. They may still want to checkpoint it, but the only source might be their current library. So the cleanest solution  (for me anyway) would be to copy that package, plus dependencies if necessary, into the checkpoint location.

**Comment by gaborcsardi** [comment]
Well, that is not supported currently, and it is not a five minutes feature to add. I will consider it, though.

**Comment by Hong-Revo** [comment]
Ta. I'd say this isn't as high priority as getting local sources to work, though.

Thinking about it a bit more, perhaps I could do this myself:

- Separate out the installed:: refs
- Copy these packages from the source to checkpoint dir, using `file.copy`
- Install all the other refs

Can you see any downsides to this?

**Comment by gaborcsardi** [comment]
Thinking about this, this is actually quite hard to implement, because I would need to lock both libraries, and then there are potential deadlock issues.

Also, on R versions before staged installation packages were allowed to record their installation location, so those packages potentially cannot be moved.

**Comment by Hong-Revo** [comment]
Yeah, maybe it's easiest for me to handle it on my end since it appears to be a rather specialised ask. I can tell people this is a tricky thing to do and caveat emptor etc.
