### ISSUE TITLE
Pkg resolution fails for Win/Mac if binary version is unavailable

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#170]
Something that appeared while testing checkpoint. If I use a snapshot that's old enough that there is no package binary available, it fails. Perhaps in this case, there should be a fallback to the source version, mimicking the behaviour of `install.packages`.

Example:

```
r$> pkgcache::pkg_cache_delete_files()
    unlink("~/insttmp", recursive=TRUE)
    inst <- new_pkg_installation_proposal(
        "R6",
        config=list(`cran-mirror`="https://mran.microsoft.com/snapshot/2018-01-01",
                    library="~/insttmp")
    )
    inst$resolve()
i Creating library directory: ~/insttmp
x Metadata update failed
Error in stop(http_error(resp)) : Not Found (HTTP 404).
```

Here, I'm using R 3.6.2, and the MRAN snapshot doesn't have binaries for that (only 3.5). Since checkpoint aims to provide access to the full MRAN archive, only being able to install binaries could be a serious problem. (I know that reproducibility becomes dodgy once you start mixing up R versions, but that's another issue.)

**Comment by gaborcsardi** [comment]
This is https://github.com/r-lib/pkgcache/issues/38
