### ISSUE TITLE
Creating install succeeds locally but fails in a CI pipeline

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#171]
(From email)

Here: https://github.com/RevolutionAnalytics/checkpoint/runs/545790007?check_suite_focus=true

I have a set of integration tests for the checkpoint v1.0 beta, and these work perfectly on my Win 10 machine but fail in a Github action.

AFAIK, the failing test should be doing just

```r
inst <- new_pkg_installation_proposal(
    c("rlang", "darts", "testpkg", "github::RevolutionAnalytics/checkpoint@testpkg"),
    config=list(`cran-mirror`="https://mran.microsoft.com/snapshot/2020-01-01", library="newdir")
)
inst$resolve()
inst$solve()
inst$download()
inst$install()
```

pkgdepends complains that the rlang.zip file is invalid, but it's definitely there. In any case, the test succeeds locally, just not in a pipeline.

The only complication I can think of is that "testpkg" doesn't exist on CRAN, but I also provide it as an explicit [Github ref](https://github.com/RevolutionAnalytics/checkpoint/tree/testpkg).

**Comment by Hong-Revo** [comment]
I've created a minimal reprex here:

https://github.com/Hong-Revo/testpkg

It's a basic package skeleton with one function and test, that runs the `new_pkg_installation_proposal` code above. The failing check is here:

https://github.com/Hong-Revo/testpkg/runs/548237066?check_suite_focus=true

cc @revodavid

**Comment by Hong-Revo** [comment]
Interestingly, `remotes::install_deps` gets confused when installing pkgdepends' dependencies, and tries to overwrite some existing packages which Windows complains about. Maybe it should use pkgdepends too. 😄

**Comment by gaborcsardi** [comment]
> Interestingly, remotes::install_deps gets confused when installing pkgdepends' dependencies, and tries to overwrite some existing packages which Windows complains about. Maybe it should use pkgdepends too. 😄

Try setting `R_REMOTES_STANDALONE="true"`, see https://github.com/r-lib/remotes#standalone-mode

**Comment by Hong-Revo** [comment]
Ta. That's dealt with the warnings, but the check failure persists.

I also ran into a failure previously on the Mac, where jsonifying one of the result objects caused an error. Something about not being able to unclass an environment. I can't reproduce it now though.

**Comment by Hong-Revo** [comment]
I found the reason for that "unable to unclass an environment" error. The `get_resolution()` method returns an object that contains a condition:

```
r$> res <- inst$get_resolution()
r$> res
# A tibble: 1 x 27
  ref   type  direct directpkg status package version license needscompilation        
  <chr> <chr> <lgl>  <lgl>     <chr>  <chr>   <chr>   <chr>   <lgl>
1 cran~ cran  TRUE   TRUE      FAILED <NA>    <NA>    <NA>    TRUE
# ... with 18 more variables: priority <chr>, md5sum <chr>, sha256 <chr>,
#   filesize <int>, built <chr>, platform <chr>, rversion <chr>, repodir <chr>,       
#   target <chr>, deps <list>, mirror <chr>, sources <list>, remote <list>,
#   error <list>, metadata <list>, extra <list>, dep_types <list>,
#   cache_status <chr>
r$> res$error
[[1]]
<async_rejected in type_cran_resolve_version(remote, direct, config, cache, dependencies): Not implemented yet>
```

The error is because I serialise these objects to json for logging purposes, and `jsonlite::toJSON` doesn't like the condition. I guess this will be fixed up before release?

**Comment by Hong-Revo** [comment]
I assumed that the "Not implemented yet" meant that it was a placeholder of some kind.

As a convenience thing, maybe consider replacing it with a more basic object (eg an error message)? Right now I can convert the condition into something else, but it requires recursing through the entire returned object and seems a bit fragile.

**Comment by gaborcsardi** [comment]
> I assumed that the "Not implemented yet" meant that it was a placeholder of some kind.

Right, but pkgdepends returns classed errors for failures, e.g. for a download failure the error object includes why the download failed.

**Comment by gaborcsardi** [comment]
Yeah, so this is basically:
```r
err <- processx:::new_error()
jsonlite::toJSON(err)
#> Error: No method asJSON S3 class: condition
```
and it could be solved by either defining an `asJSON.condition()` method, or also adding the `list` class to the conditions. FWIW base R does not do the latter, either:

```r
err <- tryCatch(1+"", error = function(e) e)
class(err)
#> [1] "simpleError" "error"       "condition"
```

OTOH I am not entirely sure who's responsibility it is to add an `asJSON` method.

**Comment by gaborcsardi** [comment]
OK, it seems that `toJSON` has a `force` argument, which you can use to drop the classes. Not great, but something:

```r
err <- processx:::new_error()
jsonlite::toJSON(err)
#> Error: No method asJSON S3 class: condition

jsonlite::toJSON(err, force = TRUE)
#> {"message":[""],"call":[true]}
```
