### ISSUE TITLE
RSPM compatibility on Linux

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdepends#183]
Right now pkgdepends hangs, most probably because it thinks that the RSPM packages are source packages. We need to be smarter to know that they are binaries.

**Comment by gaborcsardi** [comment]
It looks mostly OK, actually, but this freezes (on pkgdepend itself), in Ubuntu 16.04:

```r
library(pkgdepends)
p <- new_pkg_installation_proposal("deps::.", config = list(dependencies = TRUE))
p$resolve()
p$solve()
```

Or maybe it is just taking a long time?

**Comment by gaborcsardi** [comment]
Oh, this is probably because we have both the RSPM and CRAN repos, basically with the same contents, and this creates a combinatorial explosion in the solver.

@jimhester I believe that a workaround is to name RSPM CRAN in the `repos` option, then pak/pkgdepends will not add its own CRAN repo:
```
options(repos = c(CRAN= "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"))
```

I'll also do a proper fix.

**Comment by jimhester** [comment]
We cannot do that, we need to have both RSPM and CRAN repos because RSPM does not build packages daily and will not serve packages without built binaries. So if a new package was just released to CRAN it won't be available without the CRAN repo also set.

Re: combinatorial expansion, could you subset the available packages to just the recursive dependencies before trying to solve the installation? That would drastically reduce the size of the problem in most cases right?

**Comment by gaborcsardi** [comment]
> will not serve packages without built binaries

it does serve source packages for me. see e.g.: 

```
❯ curl -L -v -O -H 'User-Agent: R/4.0.0 (ubuntu-16.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu)' https://packagemanager.rstudio.com/cran/__linux__/xenial/latest/src/contrib/av_0.5.0.tar.gz
❯ tar tzf av_0.5.0.tar.gz | grep src
av/src/
av/src/winfunc.c
av/src/info.c
av/src/formats.c
av/src/init.c
av/src/fft.c
av/src/video.c
av/src/Makevars.win
av/src/Makevars.in
```

But yeah, I'll do a proper fix.

**Comment by gaborcsardi** [comment]
> could you subset the available packages to just the recursive dependencies

that is effectively done already. the problem is that if you have two basically identical repos, then every package has two candidates, so there are 2^100 compatible installations. Right now for pak RSPM packages are source package, once I teach it that they are (probably) binaries, that might just solve this issue. If not, then I'll have to "merge" candidates. This is already happening for CRAN and installed packages, so it is relatively easy to add. 

Anyway, I can fix this quickly I think.
