### ISSUE TITLE
Need to treat recommended packages specially

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdepends#194]
Because e.g. CRAN nlme has now `R >= 3.4`, so we cannot install it on R 3.3, and we cannot install an older version from anywhere, either. So at least we could consider the already installed recommended packages, and only install new copies of them if a newer version is required.

**Comment by jimhester** [comment]
This is also related to https://github.com/r-lib/pkgdepends/issues/189

**Comment by jimhester** [comment]
It would be great to resolve this issue in particular. It is the main thing still holding back use of pak on GitHub Actions, as this prevents checking on R 3.3.
