### ISSUE TITLE
`pkg_deps_tree()`: Circular dependencies with Remotes cause error

### ISSUE THREAD

**Issue by wch** [r-lib/pkgdepends#229]
We have a "soft" circular dependency, where shiny suggests shinytest, and shinytest imports shiny. They each list the other in the `Remotes:` field, since we're using dev versions from github. This causes an error in our CI workflow:
https://github.com/rstudio/shiny/runs/1601512829?check_suite_focus=true#step:6:32

Here's the error when I run locally in the Shiny repo directory:

```
> pak::pkg_deps_tree("local::.", dependencies = TRUE)
Error: Cannot install packages:                                
* local::.: Can't install dependency rstudio/shinytest
* rstudio/shinytest: Can't install dependency rstudio/shiny
* rstudio/shiny: Conflicts with local::.
```

**Comment by gaborcsardi** [comment]
reprex with pkgdepends:

```r
p <- pkgdepends::new_pkg_deps("local::.", config = list(dependencies = TRUE, library = lib))
p$resolve()
p$solve()
p$get_solution()
#> <pkg_solution>
#> + result: FAILED
#> + refs:
#>   - local::.
#> + constraints (515):
#>   - select shiny exactly once
#>   - select BH at most once
#>   - select Cairo at most once
#>   - select MASS at most once
#>   - select Matrix at most once
#>   - select R6 at most once
#>   - select RColorBrewer at most once
#>   - select Rcpp at most once
#>   - select assertthat at most once
#>   - select base64enc at most once
#>   ...
#> x failures:
#> * local::.: Can't install dependency rstudio/shinytest
#> * rstudio/shinytest: Can't install dependency rstudio/shiny
#> * rstudio/shiny: Conflicts with local::.
```

We could probably inspect the local directory and if it is a git repo, then use the sha of the last commit to decide if it is the same as the requested GH remote. This at least solves the GHA issue.

**Comment by gaborcsardi** [comment]
> We could probably inspect the local directory and if it is a git repo, then use the sha of the last commit to decide if it is the same as the requested GH remote.

OTOH this is pretty fragile, e.g. if there is a new commit in `rstudio/shiny` while the previous CI jobs is starting up (or you are re-running an older build manually), then the solver will still fail.

So I think we just assume that if you are installing `local::.` then you know what you are doing, and that `local::.` satisfies all dependencies on the local package.

**Comment by gaborcsardi** [comment]
@wch Once these jobs are done: https://github.com/r-lib/pak/actions?query=workflow%3A%22Build+pak+binary%22 you can try the fix.

**Comment by wch** [comment]
Looks like it worked!
