### ISSUE TITLE
pak can not find GitHub on Centos7

### ISSUE THREAD

**Issue by schloerke** [r-lib/pkgdepends#233]
I am trying to install a package using `pak` on `centos` `7`.

I can install using `remotes` and I can install packages regularly. This makes me believe I have all the required system dependencies.

Error output:
```
pak::pkg_install('r-lib/usethis')

Error: <callr_remote_error: Cannot install packages:
* r-lib/usethis: Cannot query GitHub, are you offline?>
 in process 24
-->
<simpleError: Cannot install packages:
* r-lib/usethis: Cannot query GitHub, are you offline?>

 Stack trace:

 12. (function (...)  ...
 13. base:::withCallingHandlers(cli_message = function(msg) { ...
 14. get("pkg_install_make_plan", asNamespace("pak"))(...)
 15. prop$stop_for_solution_error()
 16. private$plan$stop_for_solve_error()
 17. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
 18. base:::stop("Cannot install packages:\n", msg, call. = FALSE)
 19. base:::.handleSimpleError(function (e)  ...
 20. h(simpleError(msg, call))
 21. base:::stop(e)
 22. (function (e)  ...

 x Cannot install packages:
* r-lib/usethis: Cannot query GitHub, are you offline?
```

**Comment by gaborcsardi** [comment]
Yes, this is a bug, it happens because the embedded libcurl does not find the CA certificates for HTTPS. In theory you could work around it by setting the `CURL_CA_BUNDLE` env var to point to the file that has them, but I can't make it work, I am not sure if CentOS 7 has a file that works with curl. Anyway, we'll need to embed the certificates into pak, at least on Linux.

**Comment by gaborcsardi** [comment]
Maybe we only need to fix this in the installer: https://github.com/r-lib/pak/issues/265
Alternatively, we could fix it in pkgdepends and pkgcache etc.

**Comment by gaborcsardi** [comment]
Fixed here:
https://github.com/r-hub/actions/commit/e19362605aa721ef943c7a09ecd573fb4d153f9f
https://github.com/r-lib/pak/commit/c091cf7390f5d6035df3b890c7b4d873c22991f4
https://github.com/r-lib/pkgcache/commit/7e4aa5bc5f1e35a759374316f2fe8bf54cb07aaf
