### ISSUE TITLE
Errors from the GH API

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdepends#235]
```
x Cannot install packages:
* local::.: Can't install dependency rundel/parsermd
* rundel/parsermd: lexical error: invalid char in json text.
                                       Request forbidden by administra
                     (right here) ------^
```

This is because the User-Agent header might be missing with some newer versions of libcurl. I saw it with version 7.74.0.

**Comment by gaborcsardi** [comment]
`User-Agent` is required by GH: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required

> All API requests MUST include a valid User-Agent header. Requests with no User-Agent header will be rejected. We request that you use your GitHub username, or the name of your application, for the User-Agent header value. This allows us to contact you if there are problems.

**Comment by jeroen** [comment]
We set a default user-agent in the R bindings: https://github.com/jeroen/curl/blob/4634c1c004f15897b93faa428e136a350c9422cf/src/handle.c#L172

So I can't imagine it is missing...

**Comment by jeroen** [comment]
I can't reproduce this, user agent seems to be there:

```r
h <- new_handle()
handle_setopt(h, copypostfields = "moo=moomooo");
req <- curl::curl_fetch_memory('https://httpbin.org/post', handle = h)
cat(rawToChar(req$content))
```

**Comment by gaborcsardi** [comment]
I think it is this: https://github.com/curl/curl/issues/6312

**Comment by jeroen** [comment]
Thanks! Btw, curl 7.75.0 was just released today, which includes the fix.
