### ISSUE TITLE
field names with difference in case trigger warning in make_installed_cache()

### ISSUE THREAD

**Issue by cjyetman** [r-lib/pkgdepends#247]
If you have, for example, `readr` and `tidyverse` installed, you get this warning when running `new_pkg_deps()` (by default, I believe, only once every 8 hours due to `lifecycle` options)
``` r
library(pkgdepends)

pd <- new_pkg_deps("r-lib/pkgdepends")
#> Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
#> Using compatibility `.name_repair`.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

because `readr` uses the field "Config/Needs/website" in its DESCRIPTION file
https://github.com/tidyverse/readr/blob/c9bc0e6cdeb7d8b777c188164e9d9d516efac163/DESCRIPTION#L68

while `tidyverse` uses the field "Config/Needs/Website" in its DESCRIPTION file
https://github.com/tidyverse/tidyverse/blob/195d8a45d7ac425bb29043ca418538753b79a1b8/DESCRIPTION#L63

so when the unique fields are made lowercase here in `pkgdepends:::make_installed_cache()`
https://github.com/r-lib/pkgdepends/blob/6b225ff9080bd079a4b04e71ad025e15c21bd329/R/type-installed.R#L71

the matrix `ret` ends up with duplicate colnames, which triggers the `tibble:::as_tibble.matrix()` warning because the method of resolving duplicate colnames has not been explicitly specified here
https://github.com/r-lib/pkgdepends/blob/6b225ff9080bd079a4b04e71ad025e15c21bd329/R/type-installed.R#L80

presumably it would be ideal to not end up with duplicate column names when building the `ret` matrix, but this warning could also be squelched by explicitly specifying the `.name_repair` argument of `tibble:::as_tibble()`

**Comment by cjyetman** [comment]
FYI... tidyverse fixed the capitalization of "Website" in https://github.com/tidyverse/tidyverse/commit/72af810106d7249c905d6b0f5b8b42dc33e6ac21

but this was only an example, and the same problem is likely possible with other packages and/or with other fields

**Comment by gaborcsardi** [comment]
pkgdepends does not use tibble any more, so I guess this should not happen.
