### ISSUE TITLE
Remotes are not resolved if a package and its repo have different names

### ISSUE THREAD

**Issue by heavywatal** [r-lib/pkgdepends#263]
I have `igraphlite` package hosted at `github::heavywatal/rigraphlite`, and a dependent package with the following `DESCRIPTION`:

```
Imports:
    igraphlite
Remotes:
    github::heavywatal/rigraphlite
```

`pak::pkg_deps(".")` cannot resolve this and emits an error:
```
Error: Cannot install packages:                                            
* local::.: Can't install dependency igraphlite
* igraphlite: Can't find package called igraphlite.
```
while `remotes::install_deps()` can.

`igraphlite=github::heavywatal/rigraphlite` format suggested in #2 seems to work with `pak::pkg_deps(".")`, but it emits `Error: Unknown remote type` with `remotes::install_deps()`.

How can I satisfy both `r-lib/actions` and `devtools` system?

**Comment by gaborcsardi** [comment]
There is no way currently I am afraid, except for renaming your repository. 

You can use `pak::local_install_deps()` instead of `remotes::install_deps()`.

We could add support for the `igraphlite=github::heavywatal/rigraphlite` format in remotes, can you please open an issue there?

**Comment by heavywatal** [comment]
Thank you for the quick reply. I have just opened an issue at r-lib/remotes.

**Comment by gaborcsardi** [comment]
I'll close this issue, because we'll not change pkgdepends.
