### ISSUE TITLE
Error: Cannot select new package installation task

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdepends#306]
I am seeing build failures due to the error mentioned in the issue title, but can't seem to figure out where it's coming from. The backtrace mentions I can open an issue in this repo, and so I am checking if you might have some ideas.

Failure log: https://github.com/easystats/see/actions/runs/4427057994/jobs/7764134894
Workflow file: https://github.com/easystats/workflows/blob/main/.github/workflows/test-coverage.yaml

```r
Error: 
  ! error in pak subprocess
  Caused by error in `select_next_task(state)`:
  ! Cannot select new package installation task.
  ℹ 1 package still waiting to install: covr.
  ℹ This is an internal error in pkgdepends, please report an issue at
    <https://github.com/r-lib/pkgdepends/issues>.
  ---
  Backtrace:
  1. pak::lockfile_install(".github/pkg.lock")
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_install_internal", asNamespace("pak"))(...)
  3. plan$install()
  4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
  5. base::withCallingHandlers({ …
  6. pkgdepends:::select_next_task(state)
  7. base::throw(pkg_error("Cannot select new package installation task.", …
  8. | base::signalCondition(cond)
  9. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

**Comment by gaborcsardi** [comment]
I guess we can fix this, but it is because a circular dependency, which is probably a mistake: https://github.com/r-lib/covr/blob/caed186fc47884d1e848c09ddb9433716bd671c6/DESCRIPTION#L71

**Comment by IndrajeetPatil** [comment]
Thanks, @gaborcsardi! I can confirm that switching from `r-lib/covr` to `any::covr` solved this issue.

A bit surprised that that worked, since the CRAN version of `{covr}` also has itself in the `Suggests` field.

**Comment by gaborcsardi** [comment]
It is because `any::covr` does not install suggested packages, but `r-lib/covr` tries to.

**Comment by gaborcsardi** [comment]
This is not in our pak builds, it will be tomorrow.

**Comment by IndrajeetPatil** [comment]
I am still seeing the same error. Could this be due to a different issue?

```r
Error: 
  ! error in pak subprocess
  Caused by error in `select_next_task(state)`:
  ! Cannot select new package installation task.
  ℹ 8 packages still waiting to install: see, datawizard, performance,
    effectsize, parameters, bayestestR, report, and modelbased.
  ℹ This is an internal error in pkgdepends, please report an issue at
    <https://github.com/r-lib/pkgdepends/issues>.
```

---

Failure log: https://github.com/easystats/see/actions/runs/4470709548/jobs/7854626520?pr=271
Workflow file: https://github.com/easystats/workflows/blob/main/.github/workflows/check-readme.yaml

**Comment by gaborcsardi** [comment]
Should be really good now....

**Comment by IndrajeetPatil** [comment]
Thanks a lot, Gabor!!
