### ISSUE TITLE
`sysreqs_check_installed()` always checks for *all* dependencies

### ISSUE THREAD

**Issue by cjyetman** [r-lib/pkgdepends#361]
`sysreqs_check_installed()` doesn't appear to have a way of restricting dependencies to only "hard" dependencies, and rather always includes suggested/development dependencies.

**Comment by gaborcsardi** [comment]
Dependencies of what? It checks all the installed packages, or the ones that you specify. There is no dependency lookup happening at all. E.g.
```
> pak::sysreqs_check_installed("rhub")
system package installed required by
-------------- --        -----------
> pak::sysreqs_check_installed("curl")
system package       installed required by
--------------       --        -----------
libcurl4-openssl-dev ✔         curl
libssl-dev           ✔         curl
> pak::pkg_deps_explain("rhub", "curl")
rhub -> curl
rhub -> gert -> credentials -> curl
rhub -> whoami -> httr -> curl
```

**Comment by cjyetman** [comment]
If you have "a" package installed, `sysreqs_check_installed()` checks for all system dependencies of that package and its R pkg dependencies including "development" R pkg dependencies of that package. So for instance, it appears that if you have {DBI} installed, [which has no "hard" dependencies](https://github.com/r-dbi/DBI/blob/6382f918a56b78eb832348e0eedb538a6721286a/DESCRIPTION#L19-L41), `sysreqs_check_installed()` will report that all of the system requirements of all of the "development"/`Suggests` R packages need to be installed, as opposed to e.g. `pak::pkg_sysreqs(pkg = "DBI", sysreqs_platform = "ubuntu-22.04")`.

**Comment by gaborcsardi** [comment]
No, that's not what is happening. You get:
```
> pak::sysreqs_check_installed("DBI")
system package installed required by
```

Even though all of DBI's soft dependencies are installed:
```
-------------- --        -----------
> pak::sysreqs_check_installed()
system package       installed required by
--------------       --        -----------
cmake                ✔         arrow
libcurl4-openssl-dev ✔         arrow, curl
libicu-dev           ✔         stringi
libmysqlclient-dev   ✔         RMariaDB
libssl-dev           ✔         arrow, curl, openssl
libxml2-dev          ✔         xml2
make                 ✔         fs, sass
pandoc               ✔         knitr, rmarkdown
```

**Comment by cjyetman** [comment]
hmmmm... I'll do some more testing to see why it's happening. I (actually someone else) am not using it directly, as in `pak::sysreqs_check_installed("DBI")`, but rather running it as `pak::sysreqs_check_installed()` in a Docker container, and it's returning something like

``` r
pak::pkg_sysreqs(pkg = "DBI", sysreqs_platform = "ubuntu-22.04", dependencies = "all")
#> ── Install scripts ───────────────────────────────────────────── Ubuntu 22.04 ──
#> apt-get -y update
#> apt-get -y install libcurl4-openssl-dev libssl-dev make pandoc libicu-dev \
#>   libxml2-dev libmysqlclient-dev cmake
#> 
#> ── Packages and their system dependencies ──────────────────────────────────────
#> arrow     – cmake, libcurl4-openssl-dev, libssl-dev
#> curl      – libcurl4-openssl-dev, libssl-dev
#> fs        – make
#> knitr     – pandoc
#> openssl   – libssl-dev
#> RMariaDB  – libmysqlclient-dev
#> rmarkdown – pandoc
#> sass      – make
#> stringi   – libicu-dev
#> xml2      – libxml2-dev
```

instead of 
``` r
pak::pkg_sysreqs(pkg = "DBI", sysreqs_platform = "ubuntu-22.04")
#> ℹ Loading metadata database
#> ✔ Loading metadata database ... done
#> 
#> ── Install scripts ───────────────────────────────────────────── Ubuntu 22.04 ──
#> 
#> ── Packages and their system dependencies ──────────────────────────────────────
```

**Comment by gaborcsardi** [comment]
OK, now I am completely lost. Now you are running `pak::pkg_sysreqs()`, which is a different function.

In any case, there is no dependency lookup of any kind in `pak::sysreqs_check_installed()`. It really only checks the **installed** functions, all of them by default, as its name would suggest.

**Comment by cjyetman** [comment]
> Maybe they already have these "suggested" packages installed and the system requirements are coming from that directly instead of indirectly from having installed DBI.

ok, thanks and sorry for confusion. I think this ☝🏻 might be the reason. I'm getting notice from `pak::sysreqs_check_installed()` that I need to install `cmake` for `arrow` in an image that has `DBI` installed but has no reason to have `arrow` installed, and because `arrow` is a suggestion of `DBI` (and not of any other installed R pkg that I'm aware of), I was guessing that `pak::sysreqs_check_installed()` is reporting that because `arrow` is a suggested dependency of `DBI`.

**Comment by gaborcsardi** [comment]
For the record, there is no way to know that arrow was installed as a dependency and DBI was installed as "not a dependency".

**Comment by cjyetman** [comment]
confirmed... the Docker image had more R pkgs installed than expected. Sorry for the confusion.
