### ISSUE TITLE
Error resolving git remote

### ISSUE THREAD

**Issue by TimTaylor** [r-lib/pkgdepends#366]
I'm trying to debug a [failing action](https://github.com/reconverse/incidence2/actions/runs/9299852171/job/25594662610) where I'm setting a non-github remote. I think I've narrowed it down to pkgdepends failing to resolve something:
```R
pd <- pkgdepends::new_pkg_deps("git::https://git.sr.ht/~tim-taylor/ympes")
pd$resolve()
pd$get_resolution()$error
#> [[1]]
#> <async_rejected/rlib_error_3_0/rlib_error/error>
#> Error in `value[[3L]](cond)`:
#> ! pkgdepends resolution error for
#> git::https://git.sr.ht/~tim-taylor/ympes.
#> Caused by error: 
#> ! Failed to download 'DESCRIPTION' from git repo at
#> <https://git.sr.ht/~tim-taylor/ympes>.
#> Caused by error in `reply[[1]]`:
#> ! subscript out of bounds
```
Is this a bug in pkgdepends?

**Comment by gaborcsardi** [comment]
Probably.

**Comment by gaborcsardi** [comment]
I _suspect_ that it triggered by a git v2 server that does not have a `filter` capability. So a quick fix is to turn that on, if you can do that.

**Comment by gaborcsardi** [comment]
Will commit a fix in a minute.
