### ISSUE TITLE
Installing a package from GitHub that depends on another GitHub repo

### ISSUE THREAD

**Issue by Faizal-Eeman** [r-lib/pkgdepends#372]
Installing the package [Battenberg](https://github.com/Wedge-Oxford/battenberg/blob/master/DESCRIPTION), which depends on another repository called [ASCAT](https://github.com/VanLoo-lab), fails. The Battenberg [DESCRIPTION file](https://github.com/Wedge-Oxford/battenberg/blob/master/DESCRIPTION) only lists the dependency name, not its remote URL. Consequently, `pkgdepends` cannot locate the dependency and prevents the main package installation from completing.

Questions:

- **Ignore ASCAT dependency:** Is it possible to configure `pkgdepends` to ignore the ASCAT dependency during the Battenberg package installation?
- **Provide ASCAT source URL:** Can we provide the source URL for ASCAT to `pkgdepends` while installing Battenberg?

**Comment by gaborcsardi** [comment]
See the documentation here: https://pak.r-lib.org/reference/pak_package_sources.html#the-remotes-field

**Comment by Faizal-Eeman** [comment]
In this case, I'd have to add the `Remotes` field to a repo I don't manage. However, I was able to resolve this by simply listing the GitHub repos of the main package and dependencies in the `ref` argument.

```
pkg.download.proposal <- new_pkg_installation_proposal(
    c(
    "github-repo/dependency1",
    "github-repo/dependency2",
    "github-repo/main-package"
    )
);
pkg.download.proposal$solve();
pkg.download.proposal$download();
pkg.download.proposal$install();
```
