### ISSUE TITLE
Inferring sysreqs from cloud.r-project.org stopped working (?)

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdepends#381]
The following used to work until a few days ago

```
# using 'naked' noble on purpose
docker run --rm -it --platform linux/amd64 ubuntu:noble bash

export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y r-base-core
R -q -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'

R -q -e 'pkgs <- pak::meta_list(); pkgs[pkgs$package == "units", c("package", "sources", "sysreqs")]'
R -q -e 'pak::pak("units")'
```

Now I get

```
> pkgs <- pak::meta_list(); pkgs[pkgs$package == "units", c("package", "sources", "sysreqs")]
! Optional package `pillar` is not available for pak.
  Use `pak::pak_install_extra()` to install optional packages.
  Use `options(pak.no_extra_messages = TRUE)` to suppress this message.
v Updated metadata database: 1.69 MB in 8 files.
v Updating metadata database ... done
      package
20324   units
                                                                                                                                   sources
20324 https://cloud.r-project.org/src/contrib/units_0.8-5.tar.gz, https://cloud.r-project.org/src/contrib/Archive/units/units_0.8-5.tar.gz
      sysreqs
20324    <NA>
```

I am not sure what changed but I had to give up after several hours of research. Any idea what might have changed?

I also have some (private) CI image builds which successfully resolved the sysreqs a few days ago and now won't (without any source change).

**Comment by gaborcsardi** [comment]
Thanks! Should be fixed now, you'll need to a delete the metadata with `pak::meta_clean()` if there is any.

IDK what happened on GH Pages, but I had to do a dummy redeploy, otherwise the files where all 404.

**Comment by pat-s** [comment]
Ah, good to hear, I was already getting crazy not understanding what and *why* this was happening.

I wasn't able to find any gh-pages/github.io reference in the {pkgdepends} code. Where is it used?

PS: Working again.

**Comment by gaborcsardi** [comment]
Here: https://github.com/r-lib/pkgcache/blob/0f0a2304a4c7175b45561b0514c0099bb42919e5/R/metadata-cache.R#L416
