### ISSUE TITLE
make plan$file the path to the installed package rather than `cachedir/NA`

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkgdepends#47]
Right now the `file` column of a installation plan is set to a cache directory/NA, e.g. `"/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T//Rtmp923JLv/filea46714824832/NA"`. It would be more informative if this was the path the package was installed to.

**Comment by gaborcsardi** [comment]
Can do. It is always lib/packagename of course.

**Comment by jimhester** [comment]
I am currently returning the plan tibble from `pkgman::pkg_install()`

https://github.com/r-lib/pkgman/blob/8c1863b6c86c9f4e067860a330e1d2e5f0bbe797/R/package.R#L30

So it would more be to remind people what library path we are looking at than anything else.

**Comment by gaborcsardi** [comment]
Yeah, that's a good idea.

**Comment by gaborcsardi** [comment]
So, for already installed packages, I set `file` to proper NA, and there is a new column, `installed` that is their library directory. I decided not to use a single column for multiple purposes.
