### ISSUE TITLE
Interim spinner

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdepends#48]
When I do `pkgman::pkg_install("rstudio/rmarkdown")` there's a noticeable delay between pressing enter and seeing `✔ Resolving dependencies`. Could we get an interim spinner there? (Or maybe just move the message earlier?)

**Comment by gaborcsardi** [comment]
Yeah, this is essentially #7

**Comment by gaborcsardi** [comment]
We be closed in #7.
