### ISSUE TITLE
Support multiple cran-like repos, e.g. `release` and `rolling`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdepends#53]
and versioned install. I.e. specify `pkg@version` and get that version from `release`, or fall back to `rolling`. 

This can be either based on some implicit repo order, or some explicit priorities.

**Comment by hadley** [comment]
Most important if RSPM produces a CRAN-like repo, rather that exactly a CRAN repo.

**Comment by gaborcsardi** [comment]
Since this requires quite some planning around workflows, I am going to close this, until it is clear what we want.
