### ISSUE TITLE
Check on earlier R versions

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdepends#64]
i.e. `use_tidy_ci()`

**Comment by gaborcsardi** [comment]
Turned on in a branch, does fail on 3.1, 3.2 and on R-devel as well.....

**Comment by gaborcsardi** [comment]
To fix this, I need to fix `async` on R 3.2.x and R 3.1.x first...

**Comment by gaborcsardi** [comment]
OK, I fixed `async`...

**Comment by gaborcsardi** [comment]
R 3.2.x fixed.

**Comment by hadley** [comment]
If it's going to be expensive to get async working on 3.1, feel free to move this to the backlog. No need to get bogged done in 3.1 support.

**Comment by gaborcsardi** [comment]
No, async was easy.

**Comment by gaborcsardi** [comment]
R 3.1.x is fixed now as well, only R-devel to go.

**Comment by gaborcsardi** [comment]
Aaaan r-devel is fixed as well.
