### ISSUE TITLE
Print a log message for starting to build a package

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdepends#81]
I.e. `progress_bar$log(...)`...

**Comment by jimhester** [comment]
This should already be in pkginstall FWIW, unless you are overriding / changed the progress bar there

**Comment by gaborcsardi** [comment]
I believe that this is `pkgdepends` calling `R CMD build` to build a source package from a GH repo zip file.

**Comment by jimhester** [comment]
Yeah, but why is pkgdepends building packages in the first place? Why do you need a built package to satisfy the dependency graph?

**Comment by gaborcsardi** [comment]
`pkgdepends` provides source R packages. For that you need to call `R CMD build` on the repo.

**Comment by jimhester** [comment]
Oh right, sorry `build` / `INSTALL` confusion, I temporarily forgot where vignettes are created, carry on!

**Comment by jimhester** [comment]
I guess one question this brings up is if we should do something to prevent the need to compile a package twice. E.g. I think pkgdepends should probably always call `pkgbuild::build(vignettes = FALSE, manual = FALSE)` so we don't have to compile the package to build the vignettes / manual.

**Comment by gaborcsardi** [comment]
Yeah, we are having this conversation in two separate repos, which slightly complicates things....
