### ISSUE TITLE
System dependencies?

### ISSUE THREAD

**Issue by noamross** [r-lib/pkgdepends#94]
Not sure if this is the right place for it, but I find myself trying to solve the problem of listing all the recursive system dependencies of my package (so as to build a minimal Dockerfile for it). Can this functionality be part of this package?

**Comment by gaborcsardi** [comment]
Yes. You can already do something using https://sysreqs.r-hub.io/

E.g. calculate the recursive dependencies, and then query `https://sysreqs.r-hub.io/pkg/<pkg>`. E.g. https://sysreqs.r-hub.io/pkg/openssl

It will . be more automated in pkgdepends.

**Comment by gaborcsardi** [comment]
Linux system-dependencies from the RStudio DB are now automatically installed on the CI, on supported Linux distros. They are opt-in if `CI` is not set to `true`.
